### ISSUE TITLE
Update to LangChain V0.3 and remove Py3.8 support

### ISSUE THREAD

**Issue by averikitsch** [googleapis/langchain-google-firestore-python#101]
Recently, LangChain has released V0.3 for their libraries which removes support for Python v3.8. Other changes in this release should not affect our integrations. Python v3.8 is reaching EOL in October 2024. Therefore, we have decided to remove support for v3.8 from our libraries.

Here is an example of the changes that need to be made: https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/237. 
We recommend that you make these changes separate from the open dependency update PR (["chore(deps): update python-nonmajor"](https://github.com/googleapis/langchain-google-spanner-python/pull/89)) with the commit/PR title: "feat: remove support for Python 3.8" to ensure this change is clearly noted in the CHANGELOG.

**Comment by JU-2094** [comment]
ACKED
